### ISSUE TITLE
v1.2.1

### ISSUE THREAD

**Issue by drauggres** [versatiles-org/versatiles-fonts#5]
Hi.

Would you mind publishing bugfix release?
The version in the main branch is working, but the latest release does not.

**Comment by MichaelKreil** [comment]
There were some problems with outdated dependencies. I updated them.
Did that help? What exactly do you mean by "the latest release does not [work]"?

**Comment by drauggres** [comment]
> What exactly do you mean by "the latest release does not [work]"?

This commit was pushed after v1.2.0: https://github.com/versatiles-org/versatiles-fonts/commit/138a7fc655ab658bbf3d6d13e7cb555f83f77486
Without it you can't execute `npm run build`.

[v1.2.1](https://github.com/versatiles-org/versatiles-fonts/releases/tag/v1.2.1) is good.
Thank you!
